### ISSUE TITLE
“Monobehave”does not contain a constructor that take 1 arguments

### ISSUE THREAD

**Issue by xiaomoL444** [portra400nc/CameraTools#1]
What' wrong with this? I am poor in programing,sorry
![20220404225256](https://user-images.githubusercontent.com/69074564/161571452-0fe742cf-79c3-45d8-984c-9f81e56cd352.jpg)

**Comment by portra400nc** [comment]
Make sure all the references are added
![devenv_2022-04-05_10-17-14](https://user-images.githubusercontent.com/102507002/161666156-4f053adb-6146-46ba-9937-cec7c15f7fdc.png)
.

**Comment by xiaomoL444** [comment]
It has worked,thanks!
