### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by GangPeter** [portra400nc/CameraTools#10]
请问如何使用？[https://github.com/kagurazakasanae/MelonLoader-YuanShen](url)该项目已经不维护，加载失败。求详细的使用方法。

How to use it? [https://github.com/kagurazakasanae/MelonLoader-YuanShen](url) The project has not been maintained, loading failed. Find detailed usage methods.

**Comment by portra400nc** [comment]
dm me on discord portra#3319
