### ISSUE TITLE
Cannot inject

### ISSUE THREAD

**Issue by LLLL640** [portra400nc/CameraTools#12]
The game can be entered successfully, but pressing F9 after entering does not respond。。Only some map tool
![QQ图片20220607024917](https://user-images.githubusercontent.com/106987255/172226882-876c463c-4e79-413f-a152-54a683e51a35.png)
s

**Comment by portra400nc** [comment]
This mod requires MelonLoader which is broken for 2.7 so you can't use it unless you have a working loader (which I don't). Also that map tool you're showing is a part of Akebi-GC not CameraTools.
