### ISSUE TITLE
Injection problem

### ISSUE THREAD

**Issue by LLLL640** [portra400nc/CameraTools#13]
At present, I still enter the 2.6 version of the and enter it through the melloader. However, pressing F9 still fails to inject the camera mod. Is there a solution?

![搜狗截图22年06月07日1821_1](https://user-images.githubusercontent.com/106987255/172357319-e180e648-e1c3-475b-941b-d9faaf2ce92a.png)
![搜狗截图22年06月07日1822_2](https://user-images.githubusercontent.com/106987255/172357451-c3ae6f0a-cbad-400e-9073-822dfc775659.png)

**Comment by portra400nc** [comment]
Go to your `MelonLoader` folder, find a file called `Latest` or `Latest.log` and upload it here.

**Comment by Dio990521** [comment]
> At present, I still enter the 2.6 version of the and enter it through the melloader. However, pressing F9 still fails to inject the camera mod. Is there a solution?
> 
> ![搜狗截图22年06月07日1821_1](https://user-images.githubusercontent.com/106987255/172357319-e180e648-e1c3-475b-941b-d9faaf2ce92a.png) ![搜狗截图22年06月07日1822_2](https://user-images.githubusercontent.com/106987255/172357451-c3ae6f0a-cbad-400e-9073-822dfc775659.png)



> At present, I still enter the 2.6 version of the and enter it through the melloader. However, pressing F9 still fails to inject the camera mod. Is there a solution?
> 
> ![搜狗截图22年06月07日1821_1](https://user-images.githubusercontent.com/106987255/172357319-e180e648-e1c3-475b-941b-d9faaf2ce92a.png) ![搜狗截图22年06月07日1822_2](https://user-images.githubusercontent.com/106987255/172357451-c3ae6f0a-cbad-400e-9073-822dfc775659.png)

Where did you find the 2.6 version and a working Melonloader for it?

**Comment by portra400nc** [comment]
It's been a few days without any response, so I am assuming your problem has been solved. Feel free to re-open if you need further help.
