### ISSUE TITLE
Which version of melonloader?

### ISSUE THREAD

**Issue by incarne** [portra400nc/CameraTools#16]
Hello, this seems like a great tool id love to use. Is there a specific version of melonloader to use? I've tried installing it but no luck, the game wont open.

Also is there an exe for melonloader once its installed that I have to launch the game through or do I just load genshin through its launcher like normal?

**Comment by portra400nc** [comment]
Sadly I have no access to a working version of melonloader that works for 2.7.

**Comment by incarne** [comment]
Aw dang, well thanks for the fast reply :)
