### ISSUE TITLE
report errors

### ISSUE THREAD

**Issue by ZhongLiXiao** [portra400nc/CameraTools#3]
![%%Q}YO WLPV0%R36XZC~}4T](https://user-images.githubusercontent.com/103006565/163468795-a42f4fb8-0e09-4a4c-838e-03450cc9dcec.png)
Is there something wrong with me? He doesn't work
![}Y7CMH1W{TZV7O %`_7H19R](https://user-images.githubusercontent.com/103006565/163469227-a13669e1-fed1-44cc-ad67-45c7adf1e2fa.png)
I don't know how to use it. Sorry, I used it for the first time
After installing melloader in Genshin impact folder
CameraTools. The DLL file is in the mods folder, right?

**Comment by portra400nc** [comment]
First time I've seen that. It's not something I can solve, sorry.
