### ISSUE TITLE
Cannot open the game after installing melonloader and this tool

### ISSUE THREAD

**Issue by MXYLR** [portra400nc/CameraTools#4]
click the genshinimpact.exe and nothing happen

**Comment by portra400nc** [comment]
You need to have a melonloader build that's designed for this game. You also need a way to bypass the checksum check on top of that to actually play the game.

**Comment by Feather46** [comment]
> You need to have a melonloader build that's designed for this game. You also need a way to bypass the checksum check on top of that to actually play the game.

Can you have a detailed tutorial?
