### ISSUE TITLE
Can you please provide a complete guide?

### ISSUE THREAD

**Issue by imbugge** [portra400nc/CameraTools#6]
Hi, can you please provide a complete guide? I want to use it to make a video, can you add me to private chat? I downloaded MelonLoader and installed it to 2.5.52, but it doesn't work.

**Comment by portra400nc** [comment]
Unfortunately I can't provide links to the MelonLoader build because H*Y*v*rse will take them down. I'm pretty sure there's still forks of it so you just have to find one yourself.

**Comment by Aestheticow** [comment]
The forks links are gone.
