### ISSUE TITLE
Hi I don't know how to use the camera mod you provided

### ISSUE THREAD

**Issue by AliDva** [portra400nc/CameraTools#7]
![QQ截图20220501100107](https://user-images.githubusercontent.com/90774146/166129053-d8bcac88-26d6-47b3-810f-708eda571db1.png)

Hello, which version of MelonLoader are you using? After I used LavaGang's MelonLoader to inject into Genshin 2.6, the program could not be started. After uninstalling the MelonLoader program, it returned to normal and can be started.

**Comment by portra400nc** [comment]
There's a fork of MelonLoader that works for this game, but it got taken down. Pretty sure there's still forks of it somewhere, you just have to find one yourself.

**Comment by Aestheticow** [comment]
> There's a fork of MelonLoader that works for this game, but it got taken down. Pretty sure there's still forks of it somewhere, you just have to find one yourself.

Pretty sure everything is gone 
Can you dm me a download link?

**Comment by ZhongLiXiao** [comment]
I can't find a melon loader that Genshin can use

**Comment by LLLL640** [comment]
Could you give me a melloader that works

**Comment by LLLL640** [comment]
@portra400nc Could you give me a melloader that works
